server:
  port: 5000

branch-defaults:
  master:
    environment: analytics-env
environment-defaults:
  analytics-env:
    branch: null
    repository: null
deploy:
  artifact: build/libs/microserviceGradleJAR.jar
global:
  application_name: Analytics
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Java 8 running
    on 64bit Amazon Linux/2.7.5
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
